baseURL = "https://smallbusiness.z13.web.core.windows.net/"
languageCode = "en-us"
title = "The Architect"
theme = "coder-portfolio"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true
IsMultiLingual = false

[params]
    author = "Knight"
    description = "Knight's corner"
    keywords = "blog,developer,architect,personal"
    info = "THE ARCHITECT"
    avatarurl = "images/avatar.jpg"
    footercontent = "Architect, Developer, Thinker"
    fixedbarContent = "Do you want to know more?→"
    fixedbarContentAfter = "Thank You! Please share it if you like it→"

    hideCredits = false
    hideCopyright = false

    snsShare = true

    thumbnail = "images/tn.png"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 2

# Site Params        
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/keyurpd"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "#"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/keyurpd/"
